<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::ensureVectorExtensionExists();

        Schema::create('animes', function (Blueprint $table) {
            $table->ulid('id')
                ->primary()
                ->comment('Primary key as ULID (26-char, sortable, URL-safe).');
            $table->unsignedBigInteger('mal_id')
                ->unique()
                ->comment('MyAnimeList unique identifier. Used to deduplicate imports and link to the MAL API.');
            $table->string('title')
                ->comment('Canonical anime title as listed on MyAnimeList.');
            $table->text('description')
                ->nullable()
                ->comment('Plot synopsis or overview. Used as the source text for generating the embedding vector.');
            $table->string('image_url')
                ->nullable()
                ->comment('URL to the MAL cover image (CDN-hosted). Used for display in the UI.');
            $table->string('type')
                ->nullable()
                ->comment('Production format: TV, Movie, OVA, ONA, Special, Music, etc.');
            $table->integer('episodes')
                ->nullable()
                ->comment('Total number of episodes. Null for movies or ongoing series with unknown count.');
            $table->string('status')
                ->nullable()
                ->comment('Airing status: Finished Airing, Currently Airing, Not yet aired.');
            $table->integer('released_year')
                ->nullable()
                ->comment('Year the anime first aired. Extracted from the Premiered field in the dataset.');
            $table->json('genres')
                ->nullable()
                ->comment('Array of genre names (e.g. ["Action", "Fantasy"]). Sourced from the Genres column in the CSV.');
            $table->decimal('score', 4, 2)
                ->nullable()
                ->comment('Community score from MAL, range 1.00–10.00. Null when the anime has too few votes to be rated.');
            $table->vector('embedding', dimensions: 1536)
                ->nullable()
                ->index()
                ->comment('1536-dim vector generated by text-embedding-3-small from the title + description. Powers semantic similarity search via pgvector HNSW index.');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('animes');
    }
};
